### ISSUE TITLE
Escaping angle brackets can make the compilation fail

### ISSUE THREAD

**Issue by timotheehub** [defrancea/Projbook#119]
The following code in the .md file
"
Filter_By_\<PropertyType\>_\<PropertyName\> \<PropertyValue\>
"
generates the following exception
"
3>C:\$\Development\packages\Projbook\build\Projbook.targets(6,5): error MSB4018: The "Projbook" task failed unexpectedly.
3>C:\$\Development\packages\Projbook\build\Projbook.targets(6,5): error MSB4018: CommonMark.CommonMarkException: An error occurred during formatting of the document. ---> System.InvalidOperationException: Sequence contains no elements
3>C:\$\Development\packages\Projbook\build\Projbook.targets(6,5): error MSB4018:    at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
3>C:\$\Development\packages\Projbook\build\Projbook.targets(6,5): error MSB4018:    at Projbook.Core.Markdown.ProjbookHtmlFormatter.WriteBlock(Block block, Boolean isOpening, Boolean isClosing, Boolean& ignoreChildNodes)
3>C:\$\Development\packages\Projbook\build\Projbook.targets(6,5): error MSB4018:    at CommonMark.Formatters.HtmlFormatter.WriteDocument(Block document)
3>C:\$\Development\packages\Projbook\build\Projbook.targets(6,5): error MSB4018:    at Projbook.Core.ProjbookEngine.<Generate>c__AnonStorey1.<>m__0(Block d, TextWriter o, CommonMarkSettings s)
3>C:\$\Development\packages\Projbook\build\Projbook.targets(6,5): error MSB4018:    at CommonMark.CommonMarkConverter.ProcessStage3(Block document, TextWriter target, CommonMarkSettings settings)
3>C:\$\Development\packages\Projbook\build\Projbook.targets(6,5): error MSB4018:    --- End of inner exception stack trace ---
3>C:\$\Development\packages\Projbook\build\Projbook.targets(6,5): error MSB4018:    at CommonMark.CommonMarkConverter.ProcessStage3(Block document, TextWriter target, CommonMarkSettings settings)
3>C:\$\Development\packages\Projbook\build\Projbook.targets(6,5): error MSB4018:    at Projbook.Core.ProjbookEngine.Generate()
3>C:\$\Development\packages\Projbook\build\Projbook.targets(6,5): error MSB4018:    at Projbook.Target.Projbook.Execute()
3>C:\$\Development\packages\Projbook\build\Projbook.targets(6,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
3>C:\$\Development\packages\Projbook\build\Projbook.targets(6,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
"

**Comment by defrancea** [comment]
Thanks a lot for reporting this, I worked on a separate issue (I missed this one). This has been fixed here: https://github.com/defrancea/Projbook/issues/120 and will be part of the next release.
